### ISSUE TITLE
Performance of ATNA logging in XDS transaction

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#101]
Hi all,

during performance testing of the ITI-51 Multipatient query, we have identified that for larger lists of patient, the IPF consume a lot of time for atna logging. Since ITI-51 ATNA requires one atna for each patient id, it is clear that logging take more time than a single atna, but maybe this could be improved.

Here the extract from our jprofiler where we have queried for 1.000 patients:
![jprofiler](https://cloud.githubusercontent.com/assets/15156244/11739388/514285ce-9feb-11e5-8a08-f7623e370f9c.png)

The StringEscapeUtil seems to called very often and consume a lot of resources. Maybe there exist alternatives for this?

As a first idea to workaround we tried to use the org.openhealthtools.ihe.atna.auditor.queue.ThreadedAuditQueue, but this queue cause some problems in a spring based application:
If we just use 
```
    <bean id="iheAuditorContext"
          class="org.openhealthtools.ihe.atna.auditor.context.AuditorModuleContext"
          factory-method="getContext">
         <property name="queue">
            <bean class="org.openhealthtools.ihe.atna.auditor.queue.ThreadedAuditQueue"  />
         </property>
    </bean>
```
The application have a thread leak if the spring context shutdown, but not the jvm.

Than we have tried to invoke shutdown as part of the spring context destroy:
```
    <bean id="iheAuditorContext"
          class="org.openhealthtools.ihe.atna.auditor.context.AuditorModuleContext"
          factory-method="getContext">
         <property name="queue">
            <bean class="org.openhealthtools.ihe.atna.auditor.queue.ThreadedAuditQueue" destroy-method="shutdown" />
         </property>
    </bean>
```

But than we get the following error if the JVM shutdown as well:
```
Exception in thread "Thread-19" java.lang.NullPointerException
        at org.openhealthtools.ihe.atna.auditor.queue.ThreadedAuditQueue.shutdown(ThreadedAuditQueue.java:111)
        at org.openhealthtools.ihe.atna.auditor.queue.ThreadedAuditQueue$ThreadedAuditQueueShutdownRuntime
```

Maybe a simple "if (thread != null)" in the shutdown method could avoid this problem.

Regards,
Thomas

**Comment by ohr** [comment]
Which version of commons-lang3 have you in your dependencies? According to LANG-877 and LANG-935 there have been performance improvements in commons-lang3 3.4 regarding string escaping.

**Comment by ohr** [comment]
Yes, a check on thread != null would help.
Mid-term I would rather like to replace this class. It seems to be written back in times where there were no concurrent BlockingQueues. Or use something like https://lmax-exchange.github.io/disruptor/ .Or implement the JMSAuditQueue.

**Comment by Thopap** [comment]
Thank you for providing this information.

We had commons-lang3 3.3.2 in use. We switched to 3.4 and we see a measurable performance improvement, the time consumed in ATNA logging for our 1.000 patient query drop from around 50sec. to 15sec.

**Comment by unixoid** [comment]
@Thopap: And where are those 15 seconds spent?  Do you have an updated performance profile?

**Comment by Thopap** [comment]
Sorry, but we have no profile for the 15sec. aspect available. 

We have redone a new test with commons-lang 3.3 and directly compare with 3.4. As seen the performance improvide is noticable, but it still consume quiet a long time in the commons lang tooling.

![ipf-atna](https://cloud.githubusercontent.com/assets/15156244/11892707/11b1f248-a56b-11e5-9f05-94ada02e8ac7.png)
