### ISSUE TITLE
Wrong message structure for ITI-8 ADT_A05

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#102]
IPF says ADT_A05 HL7v2.3.1 should have message structure ADT_A05, but it's ADT_A01.
It becomes ADT_A05 in all subsequent HL7 versions, though. Confusing.

**Comment by unixoid** [comment]
Actually, IPF only echoes what IHE says -- see ITI TF-2a section 3.8.4.1.2.1.  
If you want, I could submit a change proposal to the IHE ITI committee -- shall I?

**Comment by ohr** [comment]
Ah no. 
I obviously checked the wrong revision. It was changed between 11 and 12. Never mind.

**Comment by ohr** [comment]
No changes required

**Comment by unixoid** [comment]
??
IHE TF-2a Rev. 12.0 from 18 Sep 2015 states in section 3.8.4.1.2.1 that ADT^A05 shall use message structure ADT_A05.  This message structure does not exist in HL7 v2.3.1.  So the inconsistency is still there.

**Comment by ohr** [comment]
There are no real message structures in HL7 v2.3.1 anyway.... as I said, it was changed between rev 11 (where the MSH-9-3 always shall be ADT_A01) and 12 (where the MSH-9-3 shall be ADT_A05 for A05, just like in all subsequent versions).

**Comment by unixoid** [comment]
Why do you think that there are no real message structures in HL7 v2.3.1?  They are defined in table 0354.  And IHE is not the authority which can change this table.

**Comment by ohr** [comment]
Agreed. There are. But back then I think no-one used them, and they where changed afterwards anyway. 
Shall we really propose to revert ftp://ftp.ihe.net/IT_Infrastructure/TF_Maintenance-2015/CPs/3_FinalText/from_Ballot_24/CP-ITI-786-00.doc ? 
(The HL7 chapter references from the CP are obviously wrong).

**Comment by unixoid** [comment]
Definitely we shall.  I just sent a message to the ititech list.

**Comment by unixoid** [comment]
Christian, do you know whether the class org.openehealth.ipf.commons.ihe.hl7v2.definitions.pix.v231.message.ADT_A05 and group model classes referenced from there were created manually or generated from the HL7 DB?  In the last case: is the HL7 DB corrupted as well?  A fossil bug, somehow...

**Comment by unixoid** [comment]
UPD: corrected the class name

Christian, do you know whether the class ca.uhn.hl7v2.model.v231.message.ADT_A05 and group model classes referenced from there were created manually or generated from the HL7 DB?  In the last case: is the HL7 DB corrupted as well?  A fossil bug, somehow...

**Comment by unixoid** [comment]
The change proposal accepted as CP-ITI-906 and included into the upcoming Ballot 32.

**Comment by unixoid** [comment]
Ballot 33, not 32.  Will be resolved on 20 Apr 2016.

**Comment by unixoid** [comment]
Fixed in #112.
