### ISSUE TITLE
ATNA verification fails if ParticipantObjectSensitivity is present

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#113]
We use the org.openehealth.ipf.commons.ihe.core.atna.MockedSender for ATNA verification. 

The XSD packaged with IPF contains a typo in line 486:
`ParticipantObjectSensistity` while the correct attribute name is `ParticipantObjectSensitivity`

https://gazelle.ihe.net/gss//amview/auditMessage.seam?name=IHE%20-%20DICOM%20-%20General%20Message%20Format%20Conventions

**Comment by unixoid** [comment]
DICOM PS3.15 section A.5.1 defines "...Sensistity" and not "...Sensitivity".  
The Gazelle's documentation is wrong.
But the actual validation shall not fail, because the XML Schema used by Gazelle (https://gazelle.ihe.net/XSD/tools/TLS/dicom_syslog_ext_us.xsd) is correct.
Will you inform IHE/Gazelle or shall I do it?

**Comment by unixoid** [comment]
Ok, DICOM uses "sensistity" in the schema, but "sensitivity" at all other places.  I will raise this in the IHE mailing list.

**Comment by Thopap** [comment]
The EVS client atna validation already use a different XSD validation - the ATNA that fail with the IPF validation, was successfull in the EVS client. I assume they have already updated the xsd in the EVS client, but they might have forgotten to update the Gazelle.

**Comment by unixoid** [comment]
Gazelle JIRA: https://gazelle.ihe.net/jira/browse/GSS-351

**Comment by ohr** [comment]
Yep, this was also brought up during EU connectathon. But I failed to
submit this to the official channels. My bad.

Dmytro Rud <notifications@github.com> schrieb am Fr., 3. Juni 2016 um
20:46 Uhr:

**Comment by unixoid** [comment]
from the Gazelle JIRA: "Dicom is aware of this issue. We have fixed Gazelle schemas."
