### ISSUE TITLE
Performance issue on simplified XDS model

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#121]
Hello IPF team,

while leverage more and more functionality of the IPF simplified data model, we have seen a performance degredation. Here a potential bad performing snippet from the Jprofiler: 
![xdsauthorhashcode](https://cloud.githubusercontent.com/assets/15156244/17141481/7d888826-534c-11e6-90f7-501f981d2bb3.jpg)

I could not yet provide any details how "large" this impact here is, but i assume at least the "Author" object could be improved. 

Just two ideas how to improve this handling here
- getter may locally cache their results
- org.openehealth.ipf.commons.ihe.xds.core.metadata.Hl7v2Based.isEmpty() --> maybe instead of rendering the Hapi object ("render().isEmpty()", calling "hapiObject.isEmpty()" might perform better (not sure)

Regards,
Thomas

**Comment by ohr** [comment]
Yes, hapiObject#isEmpty() did not exist yet in the early IPF days. This can be changed for sure to avoid rendering (including escaping) the contents. 
Then caching getters should not be necessary.

**Comment by unixoid** [comment]
There is a difference between `x.hapiObject.isEmpty()` and `Hl7v2Based.render(x).isEmpty()`: in the second case, only allowed components count.  E.g. a CX element like "^cx2^cx3^" is not empty from the HAPI view, but Hl7v2Based.render() will return `null`, because CX.2 and CX.3 are not used in XDS.

**Comment by ohr** [comment]
In this case, the HL7V2Based subclass could overwrite isEmpty() to only check the allowed components (like e.g. AssigningAuthority).

**Comment by unixoid** [comment]
I would like to propose a generic solution -- please take a look at my commit, and please feel free to roll it back it not suitable.  (And sorry for hijacking the issue.)

**Comment by ohr** [comment]
Looks good! 
In parallel I'm consolidating hashCode/equals/toString of these classes to use Lombok where possible, and use plain Java 7+ syntax where not...
