### ISSUE TITLE
Make OpenSAML dependency optional

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#122]
https://groups.google.com/forum/#!topic/ipf-dev/G4o6FvSAY0I

**Comment by unixoid** [comment]
SAML dependencies are factored out to the new module `ipf-commons-ihe-xua`.  In the original module `ipf-commons-ihe-ws`, a primitive plugin mechanism is implemented (primitive, because neither Camel nor Spring are available there).  To activate XUA processing, the static field `org.openehealth.ipf.commons.ihe.ws.cxf.audit.AbstractAuditInterceptor#xuaProcessor` shall be initialized with an instance of `org.openehealth.ipf.commons.ihe.xua.BasicXuaProcessor` (or other implementation of the corresponding interface).  See `org.openehealth.ipf.platform.camel.ihe.xds.iti42.TestIti42` for example.

**Comment by ohr** [comment]
I added a ServiceLoader so that including the new ipf-commons-ihe-xua module is sufficient and restores the old behavior. You can still manually override the static XuaProcessor.

**Comment by unixoid** [comment]
Thank you.  Somehow I haven't managed to find the `ServiceLoader` class %-)
