### ISSUE TITLE
Untie IHE business logic from dependency to Camel

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#123]
Although many pure IHE-related aspects of the transactions are unaware of Camel, there are still some things that can be refactored from the `ipf-platform-camel-ihe-*`  modules into `ipf-commons-ihe-*`   , e.g. `org.openehealth.ipf.platform.camel.ihe.hl7v2.HL7v2TransactionConfiguration`. Also, most singleton-style Camel component configurations, NAKFactories, Validation Profiles etc. merely contribute to a bundle of IHE transaction-specific properties rather than directly configuring Camel components and endpoints. HL7v2 and HL7v3 Fragmentation/Continuation storage can also be moved.

Factor out these configuration classes and establish sort of a "IPF IHE registry" where all transaction-specific configuration, validation profiles etc. are collected.

It would be nice to be able to provide some IHE functionality using non-Camel environments (e.g. using Vert.x, Spring Integration) in a not-too-far future

**Comment by jkiddo** [comment]
Have a look at https://github.com/jkiddo/hapi-v2-conformance-validation 

It provides IHE validation as IHE does it themselves + a semi-REST interface
