### ISSUE TITLE
CDAUtil yields error on validating IVL_INT in CDA document

### ISSUE THREAD

**Issue by jkiddo** [oehf/ipf#125]
calling org.openhealthtools.mdht.uml.cda.util.CDAUtil.validate on the document

[QRSample-11102013.txt](https://github.com/oehf/ipf/files/449463/QRSample-11102013.txt)

gives the following error: The 'validateINT' invariant is violated on 'org.openhealthtools.mdht.uml.hl7.datatypes.impl.IVL_INTImpl {urn:hl7-org:v3#//@clinicalDocument/@component/@structuredBody/@component.0/@section/@entry.0/@organizer/@component.0/@observation/@entryRelationship.0/@observation/@value.0'

As far as I can see, the document is perfectly valid

**Comment by jkiddo** [comment]
I might be related to the org.eclipse.emf.ecore of version 2.8.0.v20120606-0717 which is quite old

**Comment by unixoid** [comment]
Any chance you could take a look at #118?

**Comment by jkiddo** [comment]
I'll take a look and see what I can do

**Comment by jkiddo** [comment]
Upgrading to MDHT 3.0 solved the issue
