### ISSUE TITLE
IHE ITI Ballot 37 

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#127]

**Comment by unixoid** [comment]
I will also implement CP-810 (ATNA Audit for ITI-62).

**Comment by unixoid** [comment]
Discussion on CP-810 in the IHE mailing list: https://groups.google.com/forum/#!topic/iticomments/QIZyn21aWbQ

**Comment by unixoid** [comment]
Submitted CP-984 (ftp://ftp.ihe.net/IT_Infrastructure/TF_Maintenance/CPs/1_Assigned/CP-ITI-984-00.doc) to fix issues of CP-810.  For the time being, a temporary solution will be implemented in IPF.
