### ISSUE TITLE
Typesafe EntryUuid Setter

### ISSUE THREAD

**Issue by Tastelezz** [oehf/ipf#128]
Could you move the responsibility of how to supply a correct _EntryUuid_ in case of a _UUID_ and not a _symbolicId_ from the client to the _IPF API_?

What I do have in mind is:

``` java
org.openehealth.ipf.commons.ihe.xds.core.metadata.DocumentEntry

    public void setEntryUuid(java.util.UUID entryUuid) {
        setEntryUuid("urn:uuid:" + entryUuid.toString);
    }
```

If the _XDS Registry_ is the consumer the _EntryUuid_ may represent a _symbolicId_ or a _UUID_. Otherwise, if the _XDS Registry_ is the sender the _EntryUuid_ should always represent a _UUID_. Hence we would need three methods:

``` java
org.openehealth.ipf.commons.ihe.xds.core.metadata.DocumentEntry

    public boolean isEntryUuidSymbolic() {
        return !getEntryUuid().isPresent();
    }

    public Optional<String> getEntrySymbolicId() {
        return isEntryUuidSymbolic() ? Optional.of(this.entryUuid) : Optional.empty();
    }

    public Optional<UUID> getEntryUuid() {
        try {
            return Optional.of(UUID.fromString(this.entryUuid.substring("urn:uuid:".length())));
        } catch (RuntimeException e) {
            return Optional.empty();
        }
    }
```

**Comment by ohr** [comment]
There are UUIDs at many other places as well that might benefit... 
I therefore added some of the methods to `org.openehealth.ipf.commons.ihe.xds.core.validate.UUIDValidator`.

For setting UUID objects into uuid string setters, consider using:

```
import org.openehealth.ipf.commons.core.URN;
...
UUID uuid = ...
setEntryUUID(new URN(uuid).toString())
```
