### ISSUE TITLE
Buggy PHMR assertion

### ISSUE THREAD

**Issue by jkiddo** [oehf/ipf#129]
In 2.16.840.1.113883.10.20.9.7.ent (ipf/modules/cda/core/src/main/resources/schematron/cda_phmr/templates/2.16.840.1.113883.10.20.9.7.ent) there is an empty rule - meaning that there is nothing to assert. Running this through a schematron evaluator (eg. https://github.com/phax/ph-schematron) causes havoc. Please consider removing the follow last lines as they serve no purpose:

  <pattern id="p-2.16.840.1.113883.10.20.9.7-notes">

```
<title>HL7 PHMR Event Observation - notes validation phase</title>

<rule context='*[cda:templateId/@root="2.16.840.1.113883.10.20.9.7"]'>
</rule>
```

  </pattern>

**Comment by ohr** [comment]
Fixed as proposed.
