### ISSUE TITLE
Add support for the IHE HPD profile

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#145]
IHE spec: http://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_HPD.pdf

**Comment by ohr** [comment]
You might want to check https://gazelle.ihe.net/HPDSimulator-ejb/ProviderInformationDirectory_Service/ProviderInformationDirectory_PortType?wsdl for an alternative WSDL (except for that everything is merged into one file).
Specifically, both Soap action and WSA action have the prefix `urn:ihe:iti:hpd:2010:`. 
There has been confusion in past connectathons about this; also cf. https://groups.google.com/forum/#!topic/ihe-hpd-implementors/9vBK_4caspg.

**Comment by unixoid** [comment]
Thank you for the hint.  It seems that CP-ITI-914 (ftp://ftp.ihe.net/IT_Infrastructure/TF_Maintenance-2016/CPs/3_FinalText/from_Ballot_34/CP-ITI-914-04.doc) has not been applied to HPD.  And in Gazelle's WSDL, ":hpd:" is missing in wsa:Action of ITI-59 response (line 477).

**Comment by unixoid** [comment]
enough for the time being
