### ISSUE TITLE
Add clonable interface [Feature]

### ISSUE THREAD

**Issue by JurrianFahner** [oehf/ipf#158]
Is it possible to add a cloneable interface to all request types?

**Comment by unixoid** [comment]
Do you mean request types of all possible transactions, or only of transactions of a particular profile/profile family?

**Comment by JurrianFahner** [comment]
Especially for XDS_B, the rationale behind this is when you go from an affinity domain to cross gateway domain that sometimes you want to clone the request. There are other ways, however implementing cloneable interface is very fast performance wise.

**Comment by unixoid** [comment]
Do you mean ebXML classes or classes from the simplified model (i.e. from the package `org.openehealth.ipf.commons.ihe.xds.core.requests`)?

In the first case, my approach would be to serialize the request using JAXB and then deserialize it again, in the second case -- to use `org.apache.commons.lang3.SerializationUtils#clone`.  This will not provide the best performance, but is way easier than to write dozens of type-specific copy routines.  Any objections?

**Comment by JurrianFahner** [comment]
Answer to your first question: yes...

Well what you already mentioned, serializing gives not the best performance. So I was wondering, if it could be possible to clone the objects.... It would be a very nice feature, anyway. 

The difference between clone and other options seems to be huge: https://vyazelenko.com/2013/10/29/copy-object-in-java-performance-comparison/

If it too expensive to implement cloneable to the library (can it be automated?), then we need reside with the status quo.

**Comment by unixoid** [comment]
There are some "cloning frameworks" -- take a look at https://stackoverflow.com/questions/2156120/java-recommended-solution-for-deep-cloning-copying-an-instance -- maybe, one of them could solve your problem...

**Comment by JurrianFahner** [comment]
Thanks for your help. I decided to close this issue. 

After all it was from my perceptive a nice to have, not a should or must have.
