### ISSUE TITLE
Duplicated classes in ipf-commons-spring 3.2.1

### ISSUE THREAD

**Issue by hdconradi** [oehf/ipf#159]
In version 3.2.1 ipf-commons-spring has dependencies on ipf-commons-core and ipf-commons-map.
However, all classes from the package "org.openehealth.ipf.commons.core.config" in ipf-commons-core are duplicated in ipf-commons-spring and all classes from ipf-commons-map.

**Comment by unixoid** [comment]
Maven goal `bundle:manifest` is the one who copies classes from ipf-commons-core and ipf-commons-map into the directory ./target/classes of ipf-commons-spring (probably because ipf-commons-spring uses the same package names).

**Comment by ohr** [comment]
bundle:manifest has been dropped due to removing OSGi dupport, so this should not happen anymore
