### ISSUE TITLE
Problem with birth names in translating PIXv3 Feed requests

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#163]
Apparently there is a problem in translating birth name of patient in a PIX Feed V3 request - the translator expects birth names to be contained in a separate <name/> tag, although the spec does not give any indication that this is required.
And birth names should also contain a Name Type Code, even if they are translated into PID-6.

**Comment by unixoid** [comment]
The v2-v3 translation was somehow buggy, but this could be not discovered because message validation has been not rebased to Gazelle conformance profiles
