### ISSUE TITLE
XDS: Support repeating PID-5 and PID-11 in SourcePatientInfo

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#164]
See change proposal on ftp://ftp.ihe.net/IT_Infrastructure/TF_Maintenance/CPs/0_Incoming/CP-ITI-JRN-XDS-Clarifications%20and%20extension%20on%20sourcePatientInfo.doc

It is not yet discussed by IHE, but approval chances seem high, and a client needs it.

**Comment by unixoid** [comment]
For "standardized" HL7 fields, `PatientInfo` now offers list iterators instead of lists -- see methods `getIds()`, `getNames()`, `getAddresses()`.

A special iterator (obtained via `getHl7FieldIterator(String fieldId)`) provides access to unparsed HL7 representations of repetitions of the corresponding HL7 field and is usable for both "standardized" fields like PID-3 and PID-5, and for any others.  

Parsed and unparsed lists are automagically synchronized with each other -- this is why it was necessary to switch to iterators.

It is possible to introduce more "standardized" fields, e.g. for PID-13 and PID-14 -- please let me know.

(Some unit tests and documentation still have to be written.)

**Comment by Thopap** [comment]
Three questions / proposals for improvements:
* Patient birthdate is now truncated to the date granularity. In previous version this was not the case. Any reason for this? from specification perspective it looks valid to specify also the date+time.
* Calling the setter `sourcePatientInfo.setDateOfBirth((String)null)` will cause the PatientTransformer to render "PID-7|null", I would expect that PID-7 is omitted in that case
* XDS validation: does it make sense to add a validation step to the IPF XDS validator that all sourcePatientinfo slots matches to "PID-[any number]|...?"

**Comment by unixoid** [comment]
Validation shall be improved.
