### ISSUE TITLE
IHE ITI Ballot 43/44

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#171]
Is there anything that needs to be included?

**Comment by unixoid** [comment]
also CP-ITI-977 and CP-ITI-989

**Comment by unixoid** [comment]
IHE has not finished the work on CP-ITI-977 yet, but the discussion will not occur before Nov 30th.  We can adapt the implementation in IPF 3.5 when necessary.  

@ohr please feel free to close this issue.
