### ISSUE TITLE
XDS DocumentEntry.URI is prefixed with some invalid content

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#180]
If a XDS document is registered having defined the attribute "URI" e.g. with:
`
					<rim:Slot name="URI">
						<rim:ValueList>
							<rim:Value>http://localhost:8080/XDS/Repository/b9b9cb66-3343-450e-b28f-e9cc398024bc.xml</rim:Value>
						</rim:ValueList>
					</rim:Slot>
`

and query it again, IPF seems to rewrite the answer and prefix the result with **"1|"**:
`               <ns2:Slot name="URI">
                  <ns2:ValueList>
                     <ns2:Value>1|http://localhost:8080/XDS/Repository/b9b9cb66-3343-450e-b28f-e9cc398024bc.xml</ns2:Value>
                  </ns2:ValueList>
               </ns2:Slot>
`

It looks like org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.UriTransformer.toEbXML(String) is doing this prefixing of the URI attribute. But from the ITI spec, this looks wrong. The attribute of URI shall be a simple URI as a single value.

**Comment by unixoid** [comment]
Would it make sense to change the type of DocumentEntry.uri from String to java.net.URI?

**Comment by Thopap** [comment]
I would like to have the fix also for the 3.4-branch - and here it make sense to stay on String datatype. 

For the trunk / 3.5 it might be an improvement if URI is used as dedicated data type. The only problem that might influence the decision is the UriValidator, here there is strange comment that URI is sometimes too strict and a URL is used instead for validation purpose. Not quiet sure if this is someting from the past ...

**Comment by unixoid** [comment]
Merged to 3.4.
