### ISSUE TITLE
Issue while upgrading from IPF 2.5 to 3.0

### ISSUE THREAD

**Issue by kriti-tandon** [oehf/ipf#181]
The adapters in 2.X version of IPF had a method called putAt() which we had been using to construct HL7 messages using the HL7 fields. It was being used as below (We have all our code written in Java)-

final CompositeAdapter data = (CompositeAdapter)hl7TypeToCreate; 
data.putAt( 1, StringUtil.trim( id ) );

Now, if we want to do the same thing using Composite instead of CompositeAdapter, we do not see any method that can put values in it. 

Strangely, the interface Composite does provide a method called getComponent() (like getAt() in IPF 2.5) which is useful in retrieval of HL7 field values. There should be something like a setComponent() as well for putting in values. Or, there might be another way of doing this and I might be missing something. 

Any ideas about how this issue can be resolved would be highly appreciated. Thanks in advance!

Regards,
Kriti

**Comment by unixoid** [comment]
What about `composite.getComponent(n).parse("new value")`?

BTW, please use our mailing list [`ipf-user@googlegroups.com`](https://groups.google.com/forum/#!forum/ipf-user) for asking questions.  Github issues are intended rather for bug reports and feature proposals.

**Comment by unixoid** [comment]
Not an IPF issue.
