### ISSUE TITLE
Make IPF run/compile with Java 9+

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#184]
Need to wait for some dependencies to become Java 9 compatible...
I think we have some split packages that should be resolved sooner or later (https://blog.codefx.org/java/java-9-migration-guide/#Split-Packages)

**Comment by ohr** [comment]
Current blockers:
* https://github.com/mojohaus/jaxb2-maven-plugin/issues/99
* https://github.com/mojohaus/jaxb2-maven-plugin/issues/43

**Comment by ohr** [comment]
will create a branch for this

**Comment by ohr** [comment]
JDK 10 does not yet work due to https://github.com/rzwitserloot/lombok/issues/1572

**Comment by ohr** [comment]
See http://cxf.547215.n5.nabble.com/New-Maven-coordinates-for-Jakarta-EE-specs-td5793718.html for links to the new coordinates of JEE/EE4J Maven coordinates

**Comment by nimish** [comment]
any idea when this is planned to be merged into master?

**Comment by ohr** [comment]
This will become master once 3.7.0 is released; probably end of March
