### ISSUE TITLE
IHE ITI Ballots 45, 46, 47

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#198]

**Comment by unixoid** [comment]
Done: 749, 1069, 1106 (on 18-Mar-2018), 1108.

Open tasks:
* 1106 and 1076 are not yet finalized by IHE, I will follow up on this.
* 1079, 1097 and 1120 are related to FHIR profiles -- @ohr could you please take a look at them and decide whether and what is to be done?  Thank you!

**Comment by ohr** [comment]
FHIR CPs are mainly wording and corrections in the spec that don't require changes in the code

**Comment by unixoid** [comment]
Thank you for the clarification.
