### ISSUE TITLE
Support for RFC3881 log format

### ISSUE THREAD

**Issue by lucellebureros** [oehf/ipf#207]
RFC3881 format uses attribute name string "code". However, the codedValueType method in DICOM2016a.java statically sets the attribute name to "csd-code".  Is there any workaround to log in RFC3881 format?

![image](https://user-images.githubusercontent.com/39976868/41586529-f5b2e4a0-73e7-11e8-829d-8d7e77ea2124.png)

Reference:
https://tools.ietf.org/html/rfc3881

**Comment by ohr** [comment]
In fact we did not go that far into the past :-)
You can subclass DICOM2016a, overwrite the codedValueType method so that "code" is used as attribute name, and inject your implementation into the AuditContext with DefaultAuditContext#setSerializationStrategy(SerializationStrategy)
