### ISSUE TITLE
Cipher suites used by TLSSyslogSenderImpl.java

### ISSUE THREAD

**Issue by lucellebureros** [oehf/ipf#237]
What are the cipher suites used by TLSSyslogSenderImpl.java? 
For VertexTLSSyslogSenderImpl.java, cipher suites are from system properties as shown below:
![image](https://user-images.githubusercontent.com/39976868/45411231-a2ff3880-b6ae-11e8-855a-d8c2a6511420.png)

Does TLSSyslogSenderImpl also use cipher suites from system properties?
Is it also possible to pass cipher suites as parameters to be used by TLSSyslogSenderImpl.java?
Also, in line with this, do you support TLS profile for TLS connection for auditing? If so, where can we set the TLS profile?

**Comment by ohr** [comment]
TLSSyslogSenderImpl also uses cipher suites from system properties. The TLS client protocol can be set using the _jdk.tls.client.protocols_ environment variable.

For more detailed (or non-environment-based) configuration, you can pass in your own SSLSocketFactory implementation.
See e.g. https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html for details.
