### ISSUE TITLE
Wrong XDS ErrorCode for MetadataUpdate on missing LogicalId

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#261]
XDSTools Testcase 20000b currently complain about the wrong errorcode.

The IPF Validator produce "XDSRegistryMetadataError : Logical ID is missing on Update Document Set request"
The expected Errorcode for this kind of validation error is "XDSMetadataUpdateError"

**Comment by unixoid** [comment]
@Thopap Do you want to fix this issue by yourself or can I take it?

**Comment by Thopap** [comment]
@unixoid I appreciate your support on this topic, so you can take this issue. Thank you
