### ISSUE TITLE
ITI-62 ATNA for Server (Registry) miss required attribute

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#262]
The ATNA message for ITI-62 for the Registry do not contain required attribute ParticipantObjectDataLifeCycle:
 [EVS validator](https://gazelle.ihe.net/EVSClient/detailedResult.seam?type=ATNA&oid=1.3.6.1.4.1.12559.11.1.2.1.4.950019)

**Comment by unixoid** [comment]
This is a generic issue: How IPF can obtain values which are not present in exchanged messages.

**Comment by Thopap** [comment]
I would simply align ATNA for ITI-62 with ITI-86 and set the ParticipantObjectDataLifeCycle to "15" (PermanentErasure).  Do you see any issue with doing this?

**Comment by unixoid** [comment]
In this particular case your solution is Ok.
But sometimes there are some less comfortable prescriptions, e.g. to specify document confidentiality code and patient ID in ITI-43 audit records.  And also in ITI-62 we have to specify the object type (i.e. is this a document entry, a submission set, etc. -- see ParticipantObjectIDTypeCode).  Yes, there is always some default value we can use, but...
