### ISSUE TITLE
Validation of required mimetype attribute is missing for XDS document metadata

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#267]
The required attribute mimetype is already part of the validator of ITI-43, but currently do not yet exist for the document metadata itself (e.g. ITI-42). The ITI specification define that mimetype is required for all kind of transactions.

**Comment by unixoid** [comment]
BTW, you may consider using `StringUtils.isEmpty(mimeType)` instead of `mimeType != null && !mimeType.isEmpty()`.
