### ISSUE TITLE
Deprecate joda time in favor for java.time

### ISSUE THREAD

**Issue by JurrianFahner** [oehf/ipf#287]
According to  the [joda-time](https://www.joda.org/joda-time/) website, it is advisable to move to java.time. 

Since java 11 is LTS and has been released, it might be time to move to java.time. 

Please let me know whether I can assist in this change.

**Comment by ohr** [comment]
The 184-branch is currently being updated to run with Java 11 and Camel 3.0 (which still may take some time, unfortunately). Once this is done, it makes sense to tackle this as well. 

If you like to help, we're more than happy to accept PRs!

**Comment by ohr** [comment]
@JurrianFahner if you are still interested - the 184-branch has been stabilized and is ready for contributions!

**Comment by JurrianFahner** [comment]
@ohr Nice! I definitely want to contribute. When do you want to have this one finished (I was thinking within two weeks)?

**Comment by Thopap** [comment]
@JurrianFahner : Are you still working on this topic? I Am also interested in this change. Please let me know if you need some help with this topic.
