### ISSUE TITLE
Hl7v3NakFactory generates invalid ITI-55 response message

### ISSUE THREAD

**Issue by paidaki** [oehf/ipf#297]
When an exception is thrown from the xcpd-iti55 component, a Nak is generated using the **Hl7v3NakFactory**.

According to the specification (TF_Vol2b - Table **3.55.4.2.2.3-1**):
"The QueryAck.resultTotalQuantity, QueryAck.resultCurrentQuantity, and QueryAck.resultRemainingQuantity attributes shall not be populated."

The **Hl7v3NakFactory** (lines 190-192) should not include the three aforementioned attributes in the generated Nak, which conforms with both **ITI-47** and **ITI-55** specifications.

**Comment by ohr** [comment]
You are right for ITI-55, but not for ITI-47.

3.47.4.2.2.3 : The QueryAck.resultTotalQuantity, QueryAck.resultCurrentQuantity, and QueryAck.resultRemainingQuantity attributes SHALL have the appropriate values populated.

I don't see any exception in case of a negative acknowledgement, so I assume that these attributes shall be 0.
So probably there should be a boolean parameter that determines whether to add the quantities or not. And an extra property in Hl7v3WsTransactionConfiguration.

**Comment by paidaki** [comment]
Yes I noticed it myself, that there is not an exception in case of a negative acknowledgement, but then I tried the Gazelle validator for the ITI-47 Query Response and it seems that it is fine if these three attributes are missing, as it passes.

https://gazelle.ihe.net/EVSClient/detailedResult.seam?type=HL7v3&oid=1.3.6.1.4.1.12559.11.1.2.1.4.1518302

As I understand it, the attributes are only mandatory for the ITI-47 Continuation, so if the query fails it is only logical that the NAK does not include the three attributes (I could be wrong, as the TF does not make it clear)

So for the sake of code simplicity, we could just remove the 3 attributes from the Nak, but you are right that maybe the boolean flag would be a more appropriate solution.

**Comment by unixoid** [comment]
IPF is built not against the Gazelle validator, but against the IHE specification.  I agree to Christian, it is not correct to remove the attributes.

**Comment by paidaki** [comment]
Yes you are right. I could update the PR with a more proper solution.
