### ISSUE TITLE
Exception when converting JSON to Java

### ISSUE THREAD

**Issue by cobolus** [oehf/ipf#312]
When I try to convert a JSON string to Java object I get an exception. Sample Code:
``
ObjectMapper mapper = JsonUtils.createObjectMapper();
DocumentEntry documentEntry = mapper.readValue(jsonString, DocumentEntry.class);
``
Exception:
``
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Calendar` from String "1980-01-04T00:00:00.000 0000": not a valid representation (error: Failed to parse Date value '1980-01-04T00:00:00.000 0000': Cannot parse date "1980-01-04T00:00:00.000 0000": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))
``

**Comment by unixoid** [comment]
@cobolus Could you please provide the jsonString?

**Comment by cobolus** [comment]
`{"sourcePatientId":{"extension":"source","root":"4.1"},"sourcePatientInfo":{"id":[],"name":[{"type":null,"prefix":null,"given":null,"secondAndFurtherGiven":null,"family":"Susi","suffix":null,"degree":null}],"birthTime":{"dateTime":"1980-01-04T00:00:00.000 0000","precision":"DAY"},"gender":"M","address":[{"streetAddress":"hier","additionalLocator":null,"city":null,"county":null,"state":null,"country":null,"postalCode":null}],"other":null},"creationTime":{"dateTime":"2017-05-23T22:00:00.000 0000","precision":"SECOND"},"author":[{"authorPerson":{"id":{"extension":"id2","root":"1.2"},"name":{"type":null,"prefix":null,"given":null,"secondAndFurtherGiven":null,"family":"Norbi","suffix":null,"degree":null}},"authorInstitution":[{"idNumber":null,"assigningAuthority":null,"name":"authorOrg"}],"authorSpecialty":[{"extension":"spec1","root":"1.2.3.3"},{"extension":"spec2","root":null}],"authorRole":[{"extension":"role1","root":"1.2.3.1"},{"extension":"role2","root":null}],"authorTelecom":[]}],"legalAuthenticator":{"id":{"extension":"legal","root":"1.7"},"name":{"type":null,"prefix":null,"given":null,"secondAndFurtherGiven":null,"family":"Gustav","suffix":null,"degree":null}},"serviceStartTime":{"dateTime":"2017-05-23T22:00:00.000 0000","precision":"SECOND"},"serviceStopTime":{"dateTime":"2017-05-23T22:00:00.000 0000","precision":"SECOND"},"classCode":{"code":"57016-8","codeSystemName":"2.16.840.1.113883.6.1","displayName":"Privacy Policy Acknowledgement"},"confidentialityCode":[{"code":"N","codeSystemName":"2.16.840.1.113883.5.25","displayName":"Normal"}],"eventCode":[{"code":"TRID1001","codeSystemName":"RSNA2008 eventCodeList","displayName":"XRAY CHEST Orderable"}],"formatCode":{"code":"urn:j4care:otv:sheet:data:2016","codeSystemName":"1.3.6.1.4.1.37873.101.1.1","displayName":"Test"},"healthcareFacilityTypeCode":{"code":"HOS","codeSystemName":"2.16.840.1.113883.5.10588","displayName":"Hospital"},"languageCode":"en-US","practiceSettingCode":{"code":"309937004","codeSystemName":"2.16.840.1.113883.6.96","displayName":"Neurology department"},"typeCode":{"code":"34104-0","codeSystemName":"2.16.840.1.113883.6.1","displayName":"Consultation Note"},"repositoryUniqueId":"1.6.8.1.4.8.1.111.3.2","mimeType":"text/xml","size":247028,"hash":"278B93B978979EABD0B23D34993ED8A86ECF3A05","uri":null,"type":"stable","referenceIdList":[],"documentAvailability":null,"availabilityStatus":"Approved","comments":{"value":"TEST","language":"en-US"},"entryUuid":"urn:uuid:67f04c4c-47e8-7a44-6d96-e088f2463b83","patientId":{"extension":"A1234","root":"1.2.3.4"},"title":{"value":"Test","language":"en-US"},"uniqueId":"1.2.3.4.105000079008170054.1495628305518.3","homeCommunityId":null,"logicalUuid":"urn:uuid:67f04c4c-47e8-7a44-6d96-e088f2463b83","version":{"versionName":"1","comment":null},"limitedMetadata":false,"extraMetadata":null}`

**Comment by cobolus** [comment]
the string has been generated with:
`ObjectMapper mapper = JsonUtils.createObjectMapper();
mapper.writeValueAsString(result)
`

**Comment by cobolus** [comment]
the issue can be closed as it is an issue with the webinterface displaying and converting the date back and forth to json
