### ISSUE TITLE
CombinedXmlValidator does not validate characters in XML

### ISSUE THREAD

**Issue by tkalmar** [oehf/ipf#318]
According to the xml 1.0 spec (https://www.w3.org/TR/REC-xml/#NT-Char) not all chars are allowed in XML Files.
The combined XMLValidator allowes such chars, when they are not encoded as entity.
For example 🩳 is not allowed. When submitting an ITI-44 feed whit an patient given name of 🩳 the validator accepts the char. When giving the same char as xml entity `&#55358;&#56947;` the xml is correctly refused. (vis XSD_VALIDATOR)
This is inconsistent and leeds to a situation in our code where we can submit an iti44 feed but not read back the patient as it is encoded when read back.

**Comment by tkalmar** [comment]
I'm not 100% sure if i interpret the spec correctly and literal chars are indeed allowed to be for example `🩳`.

**Comment by unixoid** [comment]
🩳 is U+1FA73 and thus a valid XML character.
