### ISSUE TITLE
Concerns about AuditLogUsedBuilder

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#321]
I'm trying to use `AuditLogUsedBuilder` and I have several concerns about how it currently works.
First of all, here's the document I'm basing my concerns on: https://ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_RESTful-ATNA.pdf
But they are also true for the previous version 3.1.
The specification in that document conflicts with DICOM specification: http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.2

For now, I decided to use `CustomAuditMessageBuilder` instead.

### Validation
Let's have a look at this part of `validate()` method:
```
if (getMessage().findParticipantObjectIdentifications(poi -> ParticipantObjectIdTypeCode.URI.equals(poi.getParticipantObjectIDTypeCode())).size() != 1) {
    throw new AuditException("Must have exactly Audit Log Identity Participating Object ");
}
```
This ensures that there is only one `ParticipantObjectIdentification` with `ParticipantObjectIdTypeCode` set to `URI`. However, the document specifying the message does not impose such restriction: `AuditEvent Message (0..n)`. You can find this on pages 46-47 and 54-55.

### Active Participant
The method `addAccessingParticipant` currently looks like this:
```
public AuditLogUsedBuilder addAccessingParticipant(String userId,
                                                   String altUserId,
                                                   String userName,
                                                   boolean userIsRequestor,
                                                   String networkId) {
    return addActiveParticipant(
                    userId,
                    altUserId,
                    userName,
                    userIsRequestor,
                    Collections.emptyList(),
                    networkId);
}
```
It does not allow to provide `ActiveParticipantRoleId`, and in fact passes the empty list, while the documentation says that this is mandatory and should be set to `Source`, `Destination` or user's Access Control role (in case of human requestor).

### Event identification
The constructor currently looks like this:
```
public AuditLogUsedBuilder(EventOutcomeIndicator outcome,
                           String eventOutcomeDescription) {
    super();
    setEventIdentification(outcome,
            eventOutcomeDescription,
            EventActionCode.Read,
            EventIdCode.AuditLogUsed,
            null
    );
}
```
It does not allow to provide event type, which according to the document should be `EV(“ITI-81”, “IHE Transactions”, “Retrieve ATNA AuditEvent”)` or `EV(“ITI-82”, “IHE Transactions”, “Retrieve Syslog Event”)`

**Comment by ohr** [comment]
This is still code from earlier versions of ITI-81 that did not have any auditing defined. Time to catch up. We need a dedicated AuditBuilder for this.

**Validation**:
the audit events defined in ITI-81 seem to contradict what DICOM states in http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.2: there must be just one (1) Identity of the audit log
Note that AuditLogUsedBuilder (and other builders in this directory) does not know about IHE definitions, It just implements the DICOM spec.

**Active Participant**:
by extending from IHEAuditMessageBuilder, this is done automatically

**Event identification**
dto
