### ISSUE TITLE
ATNA standalone implementation 

### ISSUE THREAD

**Issue by alhersh** [oehf/ipf#339]
Hi,

Is there inside IPF a standalone implementation for ATNA? I do not want to use the whole IPF framework, I came across the following implementation:

https://github.com/oehf/ipf-oht-atna

But it seems to be deprecated.

Another question if the implementation exist, can I use it without Camel?

Thanks.

**Comment by ohr** [comment]
Check out: https://oehf.github.io/ipf-docs/docs/audit/

Maven coordinates are:

    <artifactId>ipf-commons-audit</artifactId>
    <groupId>org.openehealth.ipf.commons</groupId>

This module provides client side API and server side API (as of 4.0.0) and
does not depend on the rest of IPF.

regards
Christian

Am Fr., 22. Jan. 2021 um 14:32 Uhr schrieb Taha Alhersh <
notifications@github.com>:

**Comment by alhersh** [comment]
Hi Christian,

Many thanks for your fast prompt to my question, I really appreciate that for you.

I will consider this as closed issue for now. If I came across other issue I will let you know!

Cheers,

Taha
