### ISSUE TITLE
Possible NPEs when translating and serializing AuditMessage to FHIR AuditEvent Json

### ISSUE THREAD

**Issue by stalbrecht** [oehf/ipf#343]
When using org.openehealth.ipf.commons.ihe.fhir.support.audit.marshal.FhirAuditJsonEvent to serialize an AuditMessage, then NullPointerExceptions might occur while translating ParticipantObjectIdentifications, e.g. when the ParticipantObjectDataLifeCycle is null.

**Comment by stalbrecht** [comment]
This issue was found on IPF v3.7.4, I attached a patch file for 3.7 branch.

[patch.txt](https://github.com/oehf/ipf/files/6041316/patch.txt)

**Comment by ohr** [comment]
Thank you!
