### ISSUE TITLE
BasicXuaProcessor can not execute static method extractAssertionFromCxfMessage

### ISSUE THREAD

**Issue by Fufusulier** [oehf/ipf#346]
Hello,

I have the following issue when I try to extract the XUA token from the soap message when building an ATNA message

`groovy.lang.MissingMethodException: No signature of method: static org.openehealth.ipf.commons.ihe.xua.BasicXuaProcessor.extractAssertionFromCxfMessage() 
is applicable for argument types: (org.apache.cxf.binding.soap.SoapMessage, org.apache.cxf.headers.Header$Direction) 
values: [[org.apache.cxf.transport.Conduit:conduit: class org.apache.cxf.transport.http.URLConnectionHTTPConduit1866281916target: http://localhost:2338/services/xds/iti41, ...], ...]`

The error occurs when executing org.openehealth.ipf.commons.ihe.xua.BasicXuaProcessor#enrichAuditDatasetFromXuaToken, at  assertion = extractAssertionFromCxfMessage(message, headerDirection) ?: extractAssertionFromDom(message) (line 75)

I'm running a pretty basic java 11 Springboot application

`<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-dependencies</artifactId>
    <version>2.4.2</version>
  </parent>`

`
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        
        
        <dependency>
            <groupId>org.openehealth.ipf.boot</groupId>
            <artifactId>ipf-xds-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.openehealth.ipf.platform-camel</groupId>
            <artifactId>ipf-platform-camel-ihe-atna</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.openehealth.ipf.commons</groupId>
            <artifactId>ipf-commons-ihe-xua</artifactId>
            <version>4.0.0</version>
        </dependency>`

Any idea of what it may be? I'm not familiar with groovy at all.

**Comment by Thopap** [comment]
Not 100% sure about this, looks like a wrong grooy version might cause this:
You current load all dependencies only from spring-boot-dependencies, which still define groovy 2.5.14 while IPF 4.0 use groovy 3.0.7. Can you try either setting property `<groovy.version>3.0.7</groovy.version>` to override spring-boot default or try to import ipf-dependencies management?

**Comment by Fufusulier** [comment]
Ok thanks, I'm gonna try that

**Comment by Thopap** [comment]
@Fufusulier Have you verified the proposal? Can we close this issue?

**Comment by Fufusulier** [comment]
@Thopap Sorry I was off Yesterday. It worked. I had to put
`<groovy.version>3.0.7</groovy.version>`
and
`<dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-xml</artifactId>
            <version>${groovy.version}</version>
        </dependency>`


I'm closing the ticket, thank you.
