### ISSUE TITLE
OrderRecordBuilder validation Error

### ISSUE THREAD

**Issue by alhersh** [oehf/ipf#348]
Hello, I am trying to generate the following audit message from the OrderRecordBuilder and then validate it:
`        OrderRecordBuilder orderRecordBuilder = new OrderRecordBuilder(EventOutcomeIndicator.Success,
                "Sending message of type ", null,
                null, null);
        orderRecordBuilder.setAuditSource("ID1");
        orderRecordBuilder.addActiveParticipant("User1",null,"UserName",false,
                null,null);
        orderRecordBuilder.setEventIdentification(EventOutcomeIndicator.Success,"Description",
                EventActionCode.Read,EventId.of("110110","Code","Text"),
                EventType.of("","",""),
                PurposeOfUse.of("","",""));
        orderRecordBuilder.validate();
`
But, I am getting the following error message:
`Exception in thread "main" java.lang.NullPointerException
	at org.openehealth.ipf.commons.audit.model.AuditMessage.validate(AuditMessage.java:99)
	at org.openehealth.ipf.commons.audit.event.BaseAuditMessageBuilder.validate(BaseAuditMessageBuilder.java:73)
	at org.openehealth.ipf.commons.audit.event.OrderRecordBuilder.validate(OrderRecordBuilder.java:71)`

If I neglect the validation the following Audit message will be generated:
`<AuditMessage>
  <EventIdentification EventActionCode="R" EventDateTime="2021-03-12T13:46:15.934108300Z" EventOutcomeIndicator="0">
    <EventID csd-code="110110" codeSystemName="Code" originalText="Text" />
    <EventTypeCode csd-code="" codeSystemName="" originalText="" />
    <EventOutcomeDescription>Description</EventOutcomeDescription>
    <PurposeOfUse csd-code="" codeSystemName="" originalText="" />
  </EventIdentification>
  <ActiveParticipant UserID="User1" UserName="UserName" UserIsRequestor="false" />
  <AuditSourceIdentification AuditSourceID="ID1" />
</AuditMessage>`

I think this issue is the same as the previous issue #347.

**Comment by ohr** [comment]
Yes, this is fixed with #347. The error always occurs when no ParticipantObjectIdentification is provided
