### ISSUE TITLE
Unused ITI-8 XDS query

### ISSUE THREAD

**Issue by qligier** [oehf/ipf#351]
There a some traces of an ITI-8 XDS query (defined as `xds-iti8`) in addition to the ITI-8 PIX query (defined as `pix-iti8`), but it's not implemented.
In the code: [PIX.java:48](https://github.com/oehf/ipf/blob/master/commons/ihe/hl7v2/src/main/java/org/openehealth/ipf/commons/ihe/hl7v2/PIX.java#L48)
In the docs: [xds-iti8 component](https://oehf.github.io/ipf-docs/docs/ihe/iti8xds/)
Shouldn't this be removed?

**Comment by unixoid** [comment]
The only thing which is actually not used is the ITI_8_XDS enumeration element.  The xds-iti8 component does exist and may be already used by customers.

**Comment by qligier** [comment]
Oh right, I saw the ITI-8 component initialization with the ITI_8_PIX element, but I missed the Camel registration file for xds-iti8 (I had a filter for Java files in my code search).
Sorry for that!
