### ISSUE TITLE
ParticipantObjectIDTypeCode ignored in AuditRecordTranslator

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#359]
According to **Table 3.20.4.2.2.1-1: DICOM Audit Message Definitions represented into an AuditEvent 
Resource** in [Add RESTful ATNA (Query and Feed) Trial Implementation](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_RESTful-ATNA.pdf), as well as [6.4.7.4 DICOM Tag Mapping](http://hl7.org/fhir/R4/auditevent-mappings.html#dicom) in FHIR documentation, `entity.what` should be built from both `ParticipantObjectIdentification@ParticipantObjectID` and `ParticipantObjectIdentification.ParticipantObjectIDTypeCode`. `AuditRecordTranslator` does not use the value of `ParticipantObjectIdentification.ParticipantObjectIDTypeCode`.

From `AuditRecordTranslator`:
```groovy
    static AuditEvent.AuditEventEntityComponent participantObject(ParticipantObjectIdentificationType atna) {
        AuditEvent.AuditEventEntityComponent fhir = new AuditEvent.AuditEventEntityComponent()
        fhir.what = new Reference().setIdentifier(new Identifier(
                value: atna.participantObjectID
                /*type: codeableConcept(atna.participantObjectIDTypeCode)*/))
        fhir.type = codingEnum(new AuditEntityTypeEnumFactory().fromCode(Short.toString(atna.participantObjectTypeCode.value)))
        fhir.role = codingEnum(new ObjectRoleEnumFactory().fromCode(Short.toString(atna.participantObjectTypeCodeRole.value)))
        atna.participantObjectDetails.each {
            fhir.addDetail(new AuditEvent.AuditEventEntityDetailComponent(type: it.type, value: new Base64BinaryType(it.value)))
        }
        fhir
    }
```

**Comment by unixoid** [comment]
Nobody knows why I did this five years ago: https://github.com/oehf/ipf/commit/b749068128f1454edd5efe670da82aad43109a13

**Comment by unixoid** [comment]
@Ivan1pl : Thank you for reporting the bug.
