### ISSUE TITLE
Missing search parameter for ITI-67

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#362]
There is a new version of ITI-67 transaction specification and it defines an additional search parameter ([full list](https://profiles.ihe.net/ITI/MHD/ITI-67.html#23674121-query-search-parameters)) that is not supported in current version of [Iti67SearchParameters](https://github.com/oehf/ipf/blob/master/commons/ihe/fhir/r4/mhd/src/main/java/org/openehealth/ipf/commons/ihe/fhir/iti67/Iti67SearchParameters.java).

The missing parameter is:
**creation**: This IHE defined parameter defined as [DocumentReference-Creation](https://profiles.ihe.net/ITI/MHD/SearchParameter-DocumentReference-Creation.html), of type dateTime, specifies a search against the DocumentReference.content.attachment.creation.

**Comment by ohr** [comment]
This is basically about lifting the MHD specification from 3.2 to 4.0.1.
There is a variety of incompatible changes listed [here](https://profiles.ihe.net/ITI/MHD/a_issues.html) and we yet need to find a way to include them consistently without breaking too much for existing FHIR R4 MHD implementations. 
Proposals welcome.

**Comment by Ivan1pl** [comment]
If the versions are not compatible, then maybe (as temporary solution) have separate implementations for both versions? And make specification version part of route configuration. For example:
```java
from("mhd-iti67://serviceName?spec=old")
```
```java
from("mhd-iti67://serviceName?spec=new")
```
With new as default. For existing implementations using 3.2 specification, the only required change would be to add `?spec=old` to route configuration.

**Comment by qligier** [comment]
If that's not possible, we could also implement `mhd4-iti67` (and others).

**Comment by ohr** [comment]
MHD 4.2 support is added in IPF 3.8.0
