### ISSUE TITLE
MDHT Dependencies cannot be retrieved

### ISSUE THREAD

**Issue by gmontagu** [oehf/ipf#364]
The MDHT dependencies that are provided at https://projects.suisse-open-exchange.healthcare/artifactory/releases are failing to be retrieved by Maven builds.

For example:
`[ERROR] Failed to execute goal on project gateway: Could not resolve dependencies for project com.particlehealth:gateway:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.openehealth.ipf.modules:ipf-modules-cda-mdht:jar:4.1.0 -> org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda:jar:1.6.0-201807: Failed to read artifact descriptor for org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda:jar:1.6.0-201807: Could not transfer artifact org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda:pom:1.6.0-201807 from/to mdht-releases (https://projects.suisse-open-exchange.healthcare/artifactory/releases): transfer failed for https://projects.suisse-open-exchange.healthcare/artifactory/releases/org/openhealthtools/mdht/cda/org.openhealthtools.mdht.uml.cda/1.6.0-201807/org.openhealthtools.mdht.uml.cda-1.6.0-201807.pom: Unknown host projects.suisse-open-exchange.healthcare -> [Help 1]
[ERROR] `

The base website isn't accessible either at: https://projects.suisse-open-exchange.healthcare

**Comment by ohr** [comment]
backported to ipf-3.7

**Comment by rbastiaansen732** [comment]
Thanks for the backport!
