### ISSUE TITLE
Sample projects for multiple IHE profiles [HELP]

### ISSUE THREAD

**Issue by ziitizen** [oehf/ipf#390]
In the tutorials we have a sample implementation for XDS while being new to this, it is very hard for me to figure out what steps I will have to do for setting up other profiles e.g. XCPD, XCA, etc. Also how to set up responding gateways etc.

**Comment by Thopap** [comment]
Hello @ziitizen,

for questions, please use the IPF users mailing list: https://groups.google.com/g/ipf-user
Maybe you find a similar question there as well.

In addition, some basic aspects are also described in the documentation https://oehf.github.io/ipf-docs/docs/ihe/xds/

Best regards,
Thomas
