### ISSUE TITLE
FHIR: set HTTP headers in outgoing messages and interceptors

### ISSUE THREAD

**Issue by qligier** [oehf/ipf#402]
There are two features that I are missing from MHD (and probably all FHIR) transactions, and that I'd like to implement: setting HTTP headers and setting interceptors. 

HTTP headers could be set with a Camel header (like `OUTGOING_HTTP_HEADERS`, or reuse `FhirHttpHeaders`). It's useful in many cases, like setting the authorization or accept headers.

It would also be nice to be able to set interceptors in the endpoint URI (`?interceptors=#interceptor`), as in XDS transactions.

For the client part, I guess most of the work could be done in `FhirProducer.getClient(Exchange)`, where we can bind interceptors to the client. Since there is a client created for each transaction, we can mess with it.

It seems harder for the server part, I've no idea where to bind the interceptors. Since there's a single FHIR servlet, registering an interceptor would impact all endpoints.

**Comment by qligier** [comment]
Thanks @unixoid! Then we can close this issue.

**Comment by unixoid** [comment]
BTW, for client-side interceptors, you can set the URI parameter "hapiClientInterceptorFactories".  The parameter "hapiServerInterceptorFactories" exists as well but is not used.
