### ISSUE TITLE
Outgoing Soap headers not sent in ITI-43 transaction

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#406]
Soap headers set in `OUTGOING_SOAP_HEADERS` message header are not sent when using `ProducerTemplate`.

Route definition:
```java
from("xds-iti43:xds-iti43")
                .process("extractSecurityHeaderProcessor")
                .process("overrideExternalSamlHeaderProcessor")
                .process(e -> {
                    SoapHeader securityHeader = e.getProperty(ExchangeProperty.SECURITY_HEADER, SoapHeader.class); // WS Security header, not null
                    e.getMessage().setBody(producerTemplate.requestBodyAndHeaders(
                            url, // xds-iti43://<ip>:<port>/services/xds-iti43
                            e.getMessage().getBody(),
                            Map.of(OUTGOING_SOAP_HEADERS, Collections.singletonList(securityHeader))));
                });
```

When debugging `AbstractWsProducer` I found that the header is added to `Header.HEADER_LIST`, but then it's not sent.
REQ_OUT contains WS-Addressing headers, but not the header passed in `OUTGOING_SOAP_HEADERS` message header.

IPF version 4.4.0.

**Comment by unixoid** [comment]
Hello Mikołaj

1. The full name of the SoapHeader class you use ist
org.apache.cxf.binding.soap.SoapHeader?
2. Please make sure that you modify its field "direction" accordingly.

Best regards
Dmytro

**Comment by Ivan1pl** [comment]
Adding `securityHeader.setDirection(Header.Direction.DIRECTION_OUT);` resolved the issue.

Thank you!
