### ISSUE TITLE
Support for custom classifications in DocumentEntry

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#407]
A document repository provider we need to send documents to has defined custom classifications in their specification. The `classificationScheme` they are using does not appear anywhere in any of the official specifications, but they require such classification within `ExtrinsicObject` representing `DocumentEntry`. Would it be possible to add such feature to IPF? Perhaps as a Map in DocumentEntry and Folder, similar to `extraMetadata`? In current version they are simply ignored when converting from EbXML.

**Comment by unixoid** [comment]
Would you be OK with a List instead of a Map?  Otherwise it would be `Map<String, List<Classification>>` which is redundant and inconvenient.

**Comment by Ivan1pl** [comment]
Yes, a List would be OK.

**Comment by Thopap** [comment]
@Ivan1pl : Can you outline some more details on "their specification"? 
* Is this a national initiative somewhere or a project specific spec? is this spec somewhere public?
* What kind of data is transfered in this field? 
* Which transaction you want to extend, the ITI41 to a registry?
* Isn't it also an option to:
** build a simple camel processor which customize the SubmitObjectsRequest before sending?

**Comment by Ivan1pl** [comment]
* It is not a national initiative, definitely project specific, but the project in question is supervised by the government. I'm not sure if the specification is public, I can check and link it here if it is. I'm not sure if it will be much help though, it's all in polish.
* They use one classification for yet another document type (classCode and typeCode were apparently not enough), and another for diagnosis (ICD-10).
* ITI41 to a repository, but also ITI18 to find data submitted by other systems and ITI57 to modify/cancel our metadata.
* Yes, it can easily be done with a camel processor, I asked for it here because I think it could be a quite useful feature to have in the library, others might need it in the future

**Comment by Thopap** [comment]
So they just declare 2 addition codes, but do not use the eventCodeList for this purpose? Especially the diagnosis type is quiet often coded in the eventcodeList.
Sharing maybe one example request might be a good idea to make more clear.

**Comment by unixoid** [comment]
@Ivan1pl, you mentioned ITI-18 query.  Does the third-party registry/repository provider specify its structure?  How are the parameters for the proprietary classifications named there, which values can they have?

**Comment by Ivan1pl** [comment]
There are no examples in the specification, and sadly the specification itself is not public. They use eventCodeList for procedures (ICD-9) but not the diagnosis, for that they have their own classification. As for ITI18, what I meant was that LeafClass queries will return DocumentEntries containing the new classifications, but now as I delve deeper into their specification, I found that they do briefly mention additional query parameters for FindDocuments (for both of the new classifications, as well as one of the extra metadata slots they defined - again with no examples and in this case even parameter names or values are not specified).

**Comment by unixoid** [comment]
The commit adds support for extra classifications in Document Entries, Folders, and Submission Sets.  

What does not work is the equality check, i.e. the check whether e.g. two Document Entries containing extra classifications are logically the same --- this is because neither the JAXB stub classes nor their wrappers (e.g. `EbXMLClassification30`) implement the method `equals`.  Therefore, in the unit test, instances are compared based on their rendered representation.

Fixing this would require to re-build the whole JAXB stub using e.g. the [latest-and-greatest plugin](https://github.com/highsource/maven-jaxb2-plugin), but this can break some things (in particular, because we had to modify the JAXB generated classes), therefore I will do this only if absolutely necessary.

**Comment by unixoid** [comment]
@Ivan1pl, did you have an opportunity to test the solution?  Can I close the ticket?

**Comment by Ivan1pl** [comment]
I tested the solution in transactions: ITI-18, ITI-41, ITI-42, ITI-57; both producer and consumer side. Everything seems to be working well. Thank you!
