### ISSUE TITLE
ATNA Auditing - ITI-55 Missing PurposeOfUse

### ISSUE THREAD

**Issue by zortx233** [oehf/ipf#413]
Hello,

I was playing with the ATNA auditing for XCPD, ITI-55, and noticed the PurposeOfUse I passed in my SAML attributes wasn't getting logged.

It looks like in `Iti55AuditStrategy.groovy`, in the method `makeAuditMessage` the fourth argument to `new QueryInformationBuilder` where it passes PurposeOfUse is missing.

Current Code
```java
AuditMessage[] makeAuditMessage(AuditContext auditContext, Hl7v3AuditDataset auditDataset) {
        QueryInformationBuilder builder = new QueryInformationBuilder<>(auditContext, auditDataset, Hl7v3EventTypeCode.CrossGatewayPatientDiscovery)
```

Fixed Code
new QueryInformationBuilder<>(auditContext, auditDataset, Hl7v3EventTypeCode.CrossGatewayPatientDiscovery, **auditDataset.purposesOfUse**)

I verified locally after I added the fourth argument to pass auditDataset.purposesOfUse, that the `PurposeOfUse` element does show up in the `EventIdentification` XML element.

**Comment by unixoid** [comment]
@zortx233 Thank you for reporting and providing a solution.  I applied your patch and also found two more transactions where it was necessary.

**Comment by unixoid** [comment]
Side remark: It is not very good to pass both `auditDataset` and `auditDataset.getPurposeOfUse()` to constructors of `QueryInformationBuilder` and its siblings, but a proper refactoring would require too much effort now.  Let us wait till the IHE audit trail will be rebased onto FHIR, and then simply throw away the legacy DICOM-related code ;-)
