### ISSUE TITLE
IPF 4.6 cause NPE when mapping to XDS simplified data model

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#415]
The classification xml element that classifies the SubmissionSet does not have a "classificationScheme" and could be declared at two different places:
https://wiki.ihe.net/index.php/Notes_on_XDS_Profile#Submission_Set

After the upgrade from IPF 4.5 to 4.6, i see a NPE when processing such a submissionSet as part of a registerDocument transaction. Currently assumption: Only for "variant 2", so when Classification for the submissionSet is coded "inside" the RegistryPackage .

I assume this error is related to the change done with #407 

`	java.lang.NullPointerException.<init>() line: 60	
	java.util.Objects.requireNonNull(T) line: 221	
	java.util.ImmutableCollections$SetN<E>.contains(java.lang.Object) line: 618	
	org.openehealth.ipf.commons.ihe.xds.core.metadata.Vocabulary.isNonStandardUuid(java.lang.String) line: 294	
	org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.XDSMetaClassTransformer<E,C>.lambda$addClassificationsFromEbXML$3(org.openehealth.ipf.commons.ihe.xds.core.ebxml.EbXMLClassification) line: 236	
	org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.XDSMetaClassTransformer$$Lambda$1265.1829553277.test(java.lang.Object) line: not available	
	java.util.stream.ReferencePipeline$2$1.accept(P_OUT) line: 176	
	java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.util.function.Consumer<? super E>) line: 1655	
	java.util.stream.ReferencePipeline$2(java.util.stream.AbstractPipeline<E_IN,E_OUT,S>).copyInto(java.util.stream.Sink<P_IN>, java.util.Spliterator<P_IN>) line: 484	
	java.util.stream.ReferencePipeline$2(java.util.stream.AbstractPipeline<E_IN,E_OUT,S>).wrapAndCopyInto(S, java.util.Spliterator<P_IN>) line: 474	
	java.util.stream.ReduceOps$3(java.util.stream.ReduceOps$ReduceOp<T,R,S>).evaluateSequential(java.util.stream.PipelineHelper<T>, java.util.Spliterator<P_IN>) line: 913	
	java.util.stream.ReferencePipeline$2(java.util.stream.AbstractPipeline<E_IN,E_OUT,S>).evaluate(java.util.stream.TerminalOp<E_OUT,R>) line: 234	
	java.util.stream.ReferencePipeline$2(java.util.stream.ReferencePipeline<P_IN,P_OUT>).collect(java.util.stream.Collector<? super P_OUT,A,R>) line: 578	
	org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.SubmissionSetTransformer(org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.XDSMetaClassTransformer<E,C>).addClassificationsFromEbXML(C, E) line: 237	
	org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.SubmissionSetTransformer.addClassificationsFromEbXML(org.openehealth.ipf.commons.ihe.xds.core.metadata.SubmissionSet, org.openehealth.ipf.commons.ihe.xds.core.ebxml.EbXMLRegistryPackage) line: 113	
	org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.SubmissionSetTransformer.addClassificationsFromEbXML(org.openehealth.ipf.commons.ihe.xds.core.metadata.XDSMetaClass, org.openehealth.ipf.commons.ihe.xds.core.ebxml.EbXMLRegistryObject) line: 42	
	org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.SubmissionSetTransformer(org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.XDSMetaClassTransformer<E,C>).fromEbXML(E) line: 129	
	org.openehealth.ipf.commons.ihe.xds.core.transform.requests.RegisterDocumentSetTransformer.fromEbXML(org.openehealth.ipf.commons.ihe.xds.core.ebxml.EbXMLSubmitObjectsRequest) line: 110	
....
`

**Comment by unixoid** [comment]
@Thopap Do you want me to take this ticket?

**Comment by Thopap** [comment]
@unixoid : Since you are familiar with the changes done with #407, is was slighly my hope that you can take this ticket :-) Thanks
