### ISSUE TITLE
CXiValidator 

### ISSUE THREAD

**Issue by cyrillzadra** [oehf/ipf#416]
Is this tested value in CXiValidatorTest https://github.com/oehf/ipf/blob/28fa68d444ba276985564d0f4995358e4df0b422/commons/ihe/xds/src/test/java/org/openehealth/ipf/commons/ihe/xds/core/validate/CXiValidatorTest.java#LL34C8-L34C78 really a valid CXi field? 

Shouldn't it be -> 

`11379^^^ABCD&ISO^urn:ihe:iti:xds:2013:uniqueId^^^^`

instead of -> 

`11379^^^ABCD^urn:ihe:iti:xds:2013:uniqueId^^^^`

https://profiles.ihe.net/ITI/TF/Volume3/ch-4.2.html
_CXi.4 (Assigning Authority) shall be present when the identifier in CXi.1 is not globally unique and holds the identifier of the "domain" over which the ID Number represents a unique entity. Either Universal ID with Universal ID Type or Namespace ID is permitted._

**Comment by unixoid** [comment]
Hello Cyrill

Please take a look at the definition of the CXi data type in ITI TF-2 Table 4.2.3.1.7-2, in particular in regard of CXi.4:

> CXi.4 (Assigning Authority) shall be present when the identifier in CXi.1 is not globally unique and holds the identifier of the "domain" over which the ID Number represents a unique entity. Either Universal ID with Universal ID Type or Namespace ID is permitted.

The variant "Universal ID with Universal ID Type" from the last sentence (i.e. CXi.4.2 + CXi.4.3) would correspond to `11379^^^&1.2.3&ISO^urn:ihe:iti:xds:2013:uniqueId`, the variant "Namespace ID" (CXi.4.1) --- to `11379^^^ABCD^urn:ihe:iti:xds:2013:uniqueId`.  

Best regards
Dmytro

**Comment by cyrillzadra** [comment]
Thanks dmytro. After rereading definition it totally makes sense.  👍
