### ISSUE TITLE
Audit messages: Too many active participants that are requestors

### ISSUE THREAD

**Issue by qligier** [oehf/ipf#419]
In [IHEAuditMessageBuilder](https://github.com/oehf/ipf/blob/master/commons/ihe/core/src/main/java/org/openehealth/ipf/commons/ihe/core/atna/event/IHEAuditMessageBuilder.java#L134) (and maybe in other places), all human requestors are copied to the audit message with `userIsRequestor="true"`. If you have multiple human requestors (as in the Swiss EPR for transactions secured with XUA), then the generated audit message is invalid according to DICOM ([PS3.15 A.5.2)](https://dicom.nema.org/medical/dicom/current/output/chtml/part15/sect_A.5.2.html):

> The system shall not identify multiple participants as UserIsRequestor. If there are several known requestors, the reporting system shall pick only one as UserIsRequestor.

IPF should just choose one here. In the Swiss EPR, the last human requestor is probably the most relevant, not sure about other environments.

**Comment by unixoid** [comment]
Hi Quentin

According to section 1.6.4.3.5.1 "Specifying ActiveParticipants in ATNA records" of E1A5 EPRO-FDHA, in an EPR-related audit record there can be 0, 2, or 3 HumanUsers:
* 0 = XUA was not used (e.g. for PIXv3/PDQv3).
* 2 = HCP without ASS/TCU, or PAT, or REP.  The both repetitions denote the same person, thus it would be inconsistant to mark only one of them as requestor.
* 3 = HCP with ASS/TCU.  The first two repetitions denote the HCP, the third one -- their ASS or TCU.  In the case of HCP with ASS, I am not sure who shall be considered the actual requestor -- the HCP or the ASS.  But for the sake of simplicity, we can postulate here as well that the first two repetitions get requestor="true", and the third one gets requestor="false".

Does this sound right for you?

Best regards
Dmytro

**Comment by qligier** [comment]
I agree that it would make more sense to have the 2 or 3 humans as requestors (as implied by IHE's naming), but I think it violates DICOM's specifications. Even if the two first participants are the same human, they are still two different participants in the audit message and should not both be requestors.
Also, in the TCU case, the first participant denotes the TCU itself, not the HCP.
I am wondering if it was not a mistake to have two participants for the same human.
About which of the ASS/TCU or the HCP is the one who initiated the transaction, I guess it depends on the definition and I think there's no good answer to that.

**Comment by stephane-spahni** [comment]
Just for info, at least one requestor has to follow the "XUA" format:

> 3.40.4.2 ATNA Audit encoding
>When an ATNA Audit message needs to be generated and the user is authenticated by way of an 3960 X-User Assertion, the ATNA Audit message UserName element shall record the X-User Assertion using the following encoding:
alias<user@issuer>
where:
• alias is the optional string within the SAML Assertion's Subject element SPProvidedID 3965 attribute
• user is the required content of the SAML Assertion's Subject element
• issuer is the X-Assertion Provider entity ID contained with the content of SAML Assertion's Issuer element
• The “<” and “>” represent XML control characters 3970
Example: JD<John.Doe@example.com>

**Comment by unixoid** [comment]
> I agree that it would make more sense to have the 2 or 3 humans as requestors (as implied by IHE's naming), but I think it violates DICOM's specifications. 

How important is it to fully obey the DICOM specification?  AFAIK, even the XML Schema used for IHE audit records differs from the one DICOM created.

> Also, in the TCU case, the first participant denotes the TCU itself, not the HCP.

No.  

> I am wondering if it was not a mistake to have two participants for the same human.

No.  :-)

(Disclaimer: I am the author of the specification section I referenced above. :-) )

**Comment by unixoid** [comment]
> The first participant has the name and role of the TCU, not the HCP. Is that wrong?

Unfortunately yes.

> Anyway, if we want to be 100% compliant, we can simply set userIsRequest="false" everywhere. 

But in this case we will become incompliant with the truth.  A very important goal of audit trail (not specifically IHE ATNA, but in general) is to ensure non-repudiability of actions performed by human users.  By setting requestor="false", we free everybody from any responsibility.  "No, it wasn't me, I didn't request this action" -- will the suspected HCP say in the court -- "and look, the audit trail explicitly confirms this!"

**Comment by unixoid** [comment]
> Unfortunately yes.

OTOH, the order of HumanUser repetitions does not really matter, because it is always possible to determine the meaning of each repetition.  It is like slicing in FHIR -- you distinguish the slides based on a particular attribute instead of the position.

**Comment by qligier** [comment]
> By setting requestor="false", we free everybody from any responsibility.

I disagree, because the responsibility is decided by law, not by audit events. But if we are to have multiple requestor participants, it would probably make more sense to set `userIsRequestor="true"` to the responsible human, rather than the human/software that directly triggered the transaction.

**Comment by unixoid** [comment]
You are right of course, audit records do not enforce the law by themselves, but may serve as evidences in investigations.

**Comment by qligier** [comment]
Thanks Dmytro!
