### ISSUE TITLE
change in the documentation to use the right starter library for iti-68

### ISSUE THREAD

**Issue by adityachava2022** [oehf/ipf#425]
There should be a change in documentation in this page : https://oehf.github.io/ipf-docs/docs/boot-fhir/ where we mention about adding the starter library for MHD [ITI-68](https://oehf.github.io/ipf-docs/docs/ihe/iti68/) 
from
       ` <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-servlet-starter</artifactId>
        </dependency>`
to
        `<dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-servlet-starter</artifactId>
        </dependency>`
which contains the updated camel starter

**Comment by unixoid** [comment]
Done, thank you for reporting.
