### ISSUE TITLE
ITI-18 QueryResponse - QueryResponseTransformer submissionSet to ebXml missing objectType attribute in Classification element?

### ISSUE THREAD

**Issue by cyrillzadra** [oehf/ipf#434]
Hi all,

I am currently investigating a problem where the ITI-18 GetSubmissionSet returns a SubmissionSet containing a classification element without the attribute "objectType."

```xml
<Classification classifiedObject="urn:uuid:199493bb-6098-45d8-8bc2-2db313765df4" 
      classificationNode="urn:uuid:a54d6aa5-d40d-43f9-88c5-b4633d873bdd" 
      id="urn:uuid:8710e0f2-4ae0-4ba2-8fb4-87ed922b7844"/>
```

The mapping of SubmissionSet to ebXml seems to be happening here ->
[QueryResponseTransformer](https://github.com/oehf/ipf/blob/4220eff3f8b726727531d5db15a0b975a9e145de/commons/ihe/xds/src/main/java/org/openehealth/ipf/commons/ihe/xds/core/transform/responses/QueryResponseTransformer.java#L100)

Shouldn't a registry in the ITI-18 response have "Classification.objectType" set? Reading through the IHE spec, I found the following definition for "Classification/@objectType":

"Fixed value as specified by ebRIM. Optional upon submission of objects, `required upon retrieval`. If set, the value shall be urn:oasis:names:tc:ebxml-regrep:ObjectType:RegistryObject:Classification."

https://profiles.ihe.net/ITI/TF/Volume3/ch-4.2.html#4.2.1.2.1 - Table "4.2.1.2.1-1: XML encoding of SubmissionSet Classification"

Thanks & regards,
Cyrill

**Comment by Thopap** [comment]
Hello Cyrill,

i think you are right. Interesting to see such findings even after years of connectathons :-) (since there is no real need for this attribute at all)
I have done a short validation of a FindSubmissionSet with the EVS tool:
https://gazelle.ihe.net/evs/report.seam?oid=1.3.6.1.4.1.12559.11.11.4.8416

Even the IHE EVS validator did not indicate that topic. The Rule 43 seems to only validate the objectType of classifications "if present".

I will slightly adjust our response rendering to address this topic.

Best regards,
Thomas

**Comment by cyrillzadra** [comment]
> I have done a short validation of a FindSubmissionSet with the EVS tool: https://gazelle.ihe.net/evs/report.seam?oid=1.3.6.1.4.1.12559.11.11.4.8416
> 
> Even the IHE EVS validator did not indicate that topic. The Rule 43 seems to only validate the objectType of classifications "if present".

Yeah tried it as well and it confused me even more :-).

> I will slightly adjust our response rendering to address this topic.

Cool thanks. If you don't find time just let me know. I can try to publish this change as pr.

regards
Cyrill

**Comment by cyrillzadra** [comment]
Wow that was fast ... thanks👍

**Comment by Thopap** [comment]
Slighly extend that issue, since the objectType was misssing for RegistryPackage and ExternalIdentifier as well.
