### ISSUE TITLE
AuditRecordTranslator ignores ParticipantObjectQuery

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#446]
`AuditRecordTranslator` ignores `ParticipantObjectQuery` when translating from DICOM `AuditMessage` to FHIR `AuditEvent`. According to the [AuditEvent resource mappings specification](http://hl7.org/fhir/R4/auditevent-mappings.html#dicom), it should be mapped to `AuditEvent.entity.query`.

Adding `fhir.query = atna.participantObjectQuery` in `participantObject` method should resolve the issue.

**Comment by unixoid** [comment]
@Ivan1pl, thank you for submitting the bug report and the solution!
