### ISSUE TITLE
Implement Camel component for ITI-119 

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#462]
https://profiles.ihe.net/ITI/PDQm/ITI-119.html

**Comment by ohr** [comment]
see #448

**Comment by unixoid** [comment]
#448 is closed, but the code is not merged to master?

**Comment by ohr** [comment]
#448: Now it's merged. See ipf-commons-ihe-fhir-r4-pixpdq and ipf-platform-camel-ihe-fhir-r4-pixpdq. MatchGradeEnumInterceptor is a bit hacky

**Comment by unixoid** [comment]
Thank you!

**Comment by unixoid** [comment]
closed as duplicate
