### ISSUE TITLE
Evaluate/Consider using http://phax.github.io/ph-schematron/

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#56]
This wraps the schematron stuff somewhat nicer...

Note: internally, Saxon HE 9.5.6-1 is used. 
I already tried to upgrade to this Saxon version, but it turns out that there are problems with XmlUnit: 

in order to remove the whitespaces, it applies a XSL1 stylesheet on the document. The transformation simply returns null instead of the document with whitespaces removed. I haven't investigated this any further.

**Comment by unixoid** [comment]
Let us reopen this issue when it becomes necessary to move compilation of XSLT templates from run-time to build-time (see https://groups.google.com/forum/#!topic/ipf-dev/S3noih8eiW0).
