### ISSUE TITLE
XDS data model has string dates

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#58]
org.openehealth.ipf.commons.ihe.xds.core.metadata.DocumentEntry and org.openehealth.ipf.commons.ihe.xds.core.metadata.SubmissionSet

Some fields in the XDS model is modelled as String, but at least the setters could be more specific by adding a variant with typed parameter in order to avoid timezone issues:
* creationTime, serviceStartTime, serviceStopTime, submissionTime (Date)
* mimeType (MimeType)

**Comment by unixoid** [comment]
Can I take this issue?

**Comment by ohr** [comment]
sure go ahead

**Comment by unixoid** [comment]
When we upgrade to Java 8, we may switch to its new datetime library -- see http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html

**Comment by unixoid** [comment]
Question: which class MimeType was meant ans what would be the advantage of using it instead of String?

**Comment by ohr** [comment]
No we should not use new Java 8 DateTime API because we still want to run on JVM 7, too. We just need to make sure that we run on a JVM 8 as well.

Maybe javax.activation.MimeType, but on a second it adds no real value compared to just using a string.

**Comment by unixoid** [comment]
So you mean this issue can be closed?

**Comment by ohr** [comment]
Yes I think so
