### ISSUE TITLE
Upgrade karaf to 3.0.x (or 4.0.x)

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#59]
e.g. because of support for spring 4

**Comment by stanojevic-boris** [comment]
Some notes:
* camel-2.14.1 still does not have OSGi support for Spring 4.x
* saxon-xqj (package com.saxonica.xqj) is not part of saxon-he-9.6.0.1_2 bundles provided by servicemix project -> we need to provide our own saxon-he-osgi bundle -> check if the license allows it!!
* provide hapi-osgi bundle -> DONE

**Comment by stanojevic-boris** [comment]
* provide the ATNA OSGi bundle (2.2 with p4 Auditor) -> DONE

**Comment by ohr** [comment]
won't fix
