### ISSUE TITLE
ITI-9 response validator fails for valid PID-5

### ISSUE THREAD

**Issue by sebtacke** [oehf/ipf#66]
The PID-5 segment for an ITI-9 response is defined as  ~^^^^^^S static, resulting in an empty XPN and an XPN with the name type code S.
The gazelle profile rule (1.3.6.1.4.12559.11.1.1.30) validates that PID-5 contains two components. This results in a validation error, as org.openehealth.ipf.gazelle.validation.core.GazelleProfileRule.testSegment(Segment, SegmentType) filters the empty XPN before checking the cardinality.

**Comment by ohr** [comment]
To be precise, it's the nonEmpty() method that does this. 
Need to take care because the method is also used for removing empty segments from groups.

**Comment by ohr** [comment]
Added "RE" usage semantics: if field is empty, no validation happens (particularly with constantvalue restrictions)
