### ISSUE TITLE
Restore conditionality of validation in PIX/PDQ validating processors

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#69]
Validating processors defined in org.openehealth.ipf.platform.camel.ihe.mllp.PixPdqCamelValidators do not respect the org.openehealth.ipf.platform.camel.core.adapter.ValidatorAdapter#NEED_VALIDATION_HEADER_NAME flag any more.

**Comment by ohr** [comment]
Good catch.
Needs to be fixed in org.openehealth.ipf.platform.camel.hl7.HL7v2#validatingProcessor(HapiContext) and ConformanceProfileValidators#validatingProcessor...

**Comment by unixoid** [comment]
I will fix it on the weekend.
