### ISSUE TITLE
Information is swallowed in ValidationException's

### ISSUE THREAD

**Issue by jkiddo** [oehf/ipf#76]
When doing eg. a Schematron validation, and the document is found invalid and a ValidationException is thrown, the information of whether the collected ValidationExceptions are warnings or errors can only be found out by inspecting the getMessage on the exception. It would be great if this kind of information was accessible in other means than doing string parsing.

**Comment by unixoid** [comment]
The "outer" ValidationException now provides access to the SVRL document.
@jkiddo, please let me know whether this fits your needs.

**Comment by jkiddo** [comment]
The commit seems nice - when will it go into a release?

**Comment by unixoid** [comment]
Which branch (which version) of IPF do you use?

**Comment by jkiddo** [comment]
3.0.1

**Comment by unixoid** [comment]
@stanojevic-boris: time for 3.1? ;-)

**Comment by stanojevic-boris** [comment]
Nope, still too early for 3.1 ;) but you may merge the interesting parts into 3.0-branch and we can make the 3.0.2.

**Comment by unixoid** [comment]
Merged to 3.0.

**Comment by jkiddo** [comment]
Just to be clear - the flag value and whether its and error or warning should now be accessible one each exception, right?

**Comment by unixoid** [comment]
The whole unchanged Schematron report is now provided in the exception
object.  Whatever Saxon writes there, will be accessible, as far as I
understand the machinery behind.

OTOH, I think the IPF SchematronValidator shall be able to distinguish
between errors and warnings.  Maybe an additional parameter related to that
will be introduced in a future IPF release.

Best regards
Dmytro


2015-05-10 21:37 GMT+02:00 Jens Kristian Villadsen <notifications@github.com
