### ISSUE TITLE
IHE ITI Change Proposals Ballot 26

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#77]
http://wiki.ihe.net/index.php?title=ITI_Change_Proposals_2015#Ballot_26

**Comment by ohr** [comment]
that's mainly XCPD auditing, right?

**Comment by unixoid** [comment]
No, CP-812 was firstly implemented in IPF and then submitted to IHE ;-)
I thought rather about CP-816, but am still not sure.  It can be that no fixes will be actually necessary for Ballot 26.  Other opinions?

**Comment by unixoid** [comment]
Nothing to do.

**Comment by unixoid** [comment]
In Ballot No. 27 there is nothing to do as well.
