### ISSUE TITLE
Correct PIXv2 message structures

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#78]
See https://groups.google.com/d/msg/ipf-user/mkzlf6OJRXI/5reR-jZjZpkJ

**Comment by ohr** [comment]
The custom HL7 classes in ipf\commons\ihe\hl7v2\src\main\java\org\openehealth\ipf\commons\ihe\hl7v2\definitions\pix\v231\message do not take message structures into account. Only need A01, A05 and A39 here I guess and a proper event map in  ipf\commons\ihe\hl7v2\src\main\resources\ca\uhn\hl7v2\parser\eventmap

**Comment by unixoid** [comment]
Exactly.
My plan is to to rename ADT_A40* to ADT_A39* and add an entry to eventmap.
Question: is it not a HAPI bug that the "ADT A40 -> ADT_A39" entry in
eventmap was deleted between 2.0 and 2.2?

2015-06-10 16:14 GMT+02:00 ohr <notifications@github.com>:

**Comment by ohr** [comment]
I have to check why/when this change was done.
