### ISSUE TITLE
HL7v2 Event Map Naming conflict

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#81]
The event map for HL7v2 versions 2.3.1 and 2.5 are defined within the path ca/uhn/hl7v2/parser/eventmap/, which also also the default HAPI event maps path.

If getMessageStructureForEvent() is called, the event maps are loaded coincidentally either from the HAPI structure jar or from the ipf-commons-ihe-hl7v2 jar.

Proposal: use the path org/openehealth/ipf/commons/ihe/hl7v2/ for our event maps instead and make sure that CustomModelClassFactory#eventMapDirectory property is initialized accordingly

**Comment by ohr** [comment]
Copied eventmap to "org/openehealth/ipf/commons/ihe/hl7v2/".
This event map will be automatically used by all IHE MLLP transactions. 
For creating HL7 messages, the same eventmap location should be used as well.

**Comment by ohr** [comment]
Committed for 3.0 branch and 3.1 trunk

**Comment by unixoid** [comment]
And the old eventmaps remain in place?

**Comment by ohr** [comment]
For the time being, yes, for backwards compatibility reasons


Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Dmytro Rud <notifications@github.com> 
Datum:16.07.2015  18:56  (GMT+01:00) 
An: oehf/ipf <ipf@noreply.github.com> 
Cc: ohr <christian.ohr@gmail.com> 
Betreff: Re: [ipf] HL7v2 Event Map Naming conflict (#81) 

And the old eventmaps remain in place?
