### ISSUE TITLE
Upgrade to Camel 2.15.3 and its dependencies

### ISSUE THREAD

**Issue by unixoid** [oehf/ipf#84]
Camel 2.15.3 was released on 21 Aug 2015.
It depends from CXF 3.0.6, but this CXF version has a bug which prevents its usage in IPF -- see https://issues.apache.org/jira/browse/CXF-6517.  

Analysis: in the method org.apache.cxf.attachment.AttachmentUtil#createContentID, the namespace is parsed using "new URI(ns)", and the host name is extracted.  In IHE WS transactions (e.g. XDS), namespaces are like "urn:ihe:iti:xds-b:2007" and do not contain host names, therefore a NPE occurs later on.

CXF 3.1.2 has the same issue.

Let us try the update again when CXF 3.0.7 or CXF 3.1.3 (if nobody is against Jetty 9) will be available.

**Comment by unixoid** [comment]
Camel 2.16 uses CXF 3.1.2, which is also not good...

**Comment by ohr** [comment]
There was also a potential OOM problem due to https://issues.apache.org/jira/browse/CXF-6590, which is fixed in the more recent versions
