### ISSUE TITLE
ITI-51 response validator rejects responses containing entries for multiple patients

### ISSUE THREAD

**Issue by mario-philipps-icw** [oehf/ipf#86]
If a stored query response contains entries for multiple patients, which is the common case for ITI-51, this response is rejected by org.openehealth.ipf.platform.camel.ihe.xds.XdsCamelValidators.iti51ResponseValidator().

**Comment by unixoid** [comment]
@mario-philipps-icw, please test and let us know whether the issue can be closed.

**Comment by mario-philipps-icw** [comment]
@unixoid, after some discussions, we decided not to validate our ITI-51 responses at all. So from our side, the issue can be closed. Please let me know, if you want us to retest you fix anyway.
