### ISSUE TITLE
Initial support of FHIR

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#88]
After FHIR DSTU2 has released and a couple of IHE profile offer FHIR equivalents to legacy transactions, we should start thinking about providing some support, and how...

Most of the stuff in http://jamesagnew.github.io/hapi-fhir/ look pretty useful. FHIR interfaces can be exposed as Camel consumers and producers, although there is not much obvious overlap with existing Camel ReST functionality. Resource Handlers are identified pretty statically by using annotations. 
At least we could offer the usual ATNA auditing, logging etc. stuff.

I would also propose to take PIXm (ITI-83) as an "easy" IHE transaction for nailing down how this can be done using general IPF mechanisms.

Whatever we do should happen an on branch

Comments welcome!

**Comment by unixoid** [comment]
I find this idea very opportune and will be happy to contribute starting from mid-November.

**Comment by jkiddo** [comment]
Sounds great - I'll see if I have some time too

**Comment by unixoid** [comment]
Sorry, occasionally committed a fix for #89 here.

**Comment by ohr** [comment]
Created a "fhir" branch for ipf and ipf-oht-atna

**Comment by ohr** [comment]
verify implementation against IHE ballot #32 (PIXm/PDQm in DSTU2)

**Comment by ohr** [comment]
additional issues will be opened for improvements of FHIR support
