### ISSUE TITLE
Request validation of ITI18 request does not reflect new logicalID parameter

### ISSUE THREAD

**Issue by essagl** [oehf/ipf#89]
http://ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_XDS_Metadata_Update.pdf
3.18.4.1.2.3.7.5 GetDocuments 
Retrieve a collection of XDSDocumentEntry objects. XDSDocumentEntry objects are selected 
either by their entryUUID or uniqueID, or logicalID attribute.

Please fix
org.openehealth.ipf.commons.ihe.xds.core.validate.requests.AdhocQueryRequestValidator
Line 330
new ChoiceValidation(DOC_ENTRY_UUID, DOC_ENTRY_UNIQUE_ID), and add DOC_ENTRY_LOGICAL_ID

**Comment by unixoid** [comment]
@essagl, thanks for reporting.  Fixed it for GetFolders as well -- see commit b67d710.  Please test and let us know whether the issue can be closed.
