### ISSUE TITLE
ITI-51 multi patient query with invalid patient ID separator does not cause error

### ISSUE THREAD

**Issue by mario-philipps-icw** [oehf/ipf#94]
We sent an ITI-51 multi patient query with multiple patient IDs in the same `<value>`. However, the IDs were separated with ";" instead of ",".

Example:
```xml
<Slot name="$XDSDocumentEntryPatientId">
    <ValueList>
        <Value>('1^^^&amp;1.2.3.4&amp;ISO';'2^^^&amp;1.2.3.4&amp;ISO')</Value>
    </ValueList>
</Slot>
```

Our expectation was, that the `org.openehealth.ipf.platform.camel.ihe.xds.XdsCamelValidators.iti51RequestValidator()` rejects the query. However, the request passed the validator, and the `org.openehealth.ipf.commons.ihe.xds.core.requests.QueryRegistry` contained only the first patient ID.

Can you please fix this also in the 3.0 version?

**Comment by Thopap** [comment]
Just one additional note.
IHE TF Vol2 3.18.4.1ff mention the format for queries. Here the "," is the separator for multiple values.

IHE TF Vol3 4.2.3.1.7-2 mention the format the format for patientId's (HL7 CX)
