### ISSUE TITLE
Inconvenient dependency to Spring DI framework

### ISSUE THREAD

**Issue by jkiddo** [oehf/ipf#95]
The MllpEndpointConfiguration (https://github.com/oehf/ipf/blob/master/platform-camel/ihe/mllp/src/main/java/org/openehealth/ipf/platform/camel/ihe/mllp/core/MllpEndpointConfiguration.java#L100) has a really inconvenient cast to a SpringCamelContext when one (meaining me) are using Google Guice instead of Spring. I'm pretty new to this framework so the question goes like this: Is this framework heavily dependent on Spring, or would it be considered as possible to use eg. Guice instead of Spring. This is only the first gotcha I've come upon and I would love to contribute to the project - as long as it is not going to be painful all the way ... ;)

**Comment by ohr** [comment]
Jens, unfortunately there are Spring dependencies scattered all over IPF... 
I definitely want to isolate these dependencies and/or make them optional, but currently there are no concrete plans to do so in the very near future.

**Comment by jkiddo** [comment]
So what you are saying is that I'm only scratching the surface? If you had to put a number of hours on an estimate - what would that be +100 hours or more?

**Comment by ohr** [comment]
Guess it takes a walk through the codebase for an estimate - there are certainly places where Spring dependencies could be avoided (like the one you spotted, where looking up the Registry abstraction of Camel would be sufficient), and other areas where it's likely more difficult. 
Stay tuned.

**Comment by ohr** [comment]
Looks doable. 
* Often, just Spring abstractions and utilities (Resource, BeanUtils, SpELExpressions, ConversionService) are used. 
* Sometimes, there are InitializingBean/DisposableBean interfaces implemented, or dependencies are @Autowired, but this can be easily removed.
* commons-core can be split into two modules, isolating Spring dependencies
* The dynamic configuration (http://oehf.github.io/ipf/dynamic.html) depends on Spring Lifecycle events, so for the time being it will remain this way. 
* The FlowManager modules used @ManagedMBeans and Spring Hibernate support, but these modules are not part of the core IPF interface functionality anyway.

Most Spring dependencies are in test cases, which is perfectly ok.

**Comment by jkiddo** [comment]
It sounds sane ... I'm totally green in Spring - but pretty familiar with Guice. Now I just need to find a place to start

**Comment by jkiddo** [comment]
Okay ... so I've checked out the entire ipf project and imported the entire bundle into eclipse as ordinary maven projects ... so far so good. However some of the projects contains both Java and Groovy code and within the project the Java code refers to some of the Groovy classes (for instance org.openehealth.ipf.platform.camel.ihe.mllp.core.intercept.AuditInterceptorUtils refers to the Groovy class org.openehealth.ipf.platform.camel.ihe.mllp.core.AuditUtils). As far as I can read, this is a bit of a problem - or is it just me that does not use the right plugins?

**Comment by ohr** [comment]
OK, so the trunk now has a somewhat de-springified dependency structure, with all mandatory Spring dependencies in new module ipf-commons-spring.

ipf-commons-flow and ipf-platform-camel-flow still depend on Spring, too.

**Comment by ohr** [comment]
Added documentation
